export type SettingsLinks =
    | "USER_PROFILE"
    | "USER_MANAGER"
    | "ROLE_MANAGER"
    | "TOPIC_MANAGER"
    | "INTEGRATIONS"
    | "TEAM_MANAGER"
    | "AUDIT_MANAGER"
    | "VIOLATION_MANAGER"
    | "RECORDING_MANAGER"
    | "CALL_TYPE_MANAGER"
    | "CALL_TAGS_MANAGER"
    | "BILLING"
    | "SCHEDULED_REPORTS";
